/**
 * @file output_coverage.h
 * @brief Coverage-output utilities for exporting per-base coverage data.
 *
 * This module provides functions for writing coverage results generated by
 * CDX analyses to output files. Coverage information is represented as
 * flattened per-base tables, with component boundary metadata used to map
 * coverage values back to their originating components. The output routines
 * validate input consistency and serialize coverage data into tabular formats
 * suitable for downstream analysis, debugging, and reporting.
 */

#ifndef CDX_COVERAGE_OUTPUT_COVERAGE_H
#define CDX_COVERAGE_OUTPUT_COVERAGE_H

#include "cdx_types.h"

#include <filesystem>
#include <string>
#include <vector>

namespace output {

    /**
     * @brief Writes a coverage TSV (Tab-Separated Values) query report for a specific genomic component.
     *
     * This function exports base-pair coverage data into a TSV format using a high-performance
     * double-buffered writer. It filters out positions that exceed or equal the `cfg::NOT_IN_QUERY`
     * threshold.
     *
     * @param output_tsv The file path where the output TSV file will be written.
     * @param bp_cov_table A vector containing coverage values indexed by position.
     * @param component_name The name of the component being processed (must not be empty).
     *
     * @throws std::invalid_argument If @p component_name is empty.
     * @throws std::runtime_error If the output file cannot be opened or if flushing fails.
     */
    void writeCoverageTsvQuery(
        const std::filesystem::path& output_tsv,
        const std::vector<cdx::Coverage>& bp_cov_table,
        const std::string& component_name
    );

    /**
     * @brief Write global coverage values to a TSV file using component-relative coordinates.
     *
     * The coverage table is provided as a single flattened array containing the
     * coverage values for all components. The bp_component_offsets vector defines
     * the start and end boundaries of each component within that flattened array,
     * while component_names supplies the corresponding component identifiers.
     *
     * Output rows contain the component name, the position relative to the start
     * of that component, and the coverage value. Coverage entries with sentinel
     * values greater than or equal to cfg::NOT_IN_QUERY are omitted from the
     * output.
     *
     * @param output_tsv Path to the TSV file to create.
     * @param flat_bp_cov_table Flattened per-base coverage table across all components.
     * @param bp_component_offsets Component boundary offsets into
     *        flat_bp_cov_table. Must start at 0, be non-decreasing, and contain
     *        one additional offset marking the end of the final component.
     * @param component_names Names corresponding to the component intervals
     *        described by bp_component_offsets.
     *
     * @throws std::invalid_argument If the component boundaries or names are
     *         inconsistent with the coverage table.
     * @throws std::runtime_error If the output file cannot be opened or flushed.
     */
    void writeCoverageTsvGlobal(
        const std::filesystem::path& output_tsv,
        const std::vector<cdx::Coverage>& flat_bp_cov_table,
        const std::vector<cdx::PosBp>& bp_component_offsets,
        const std::vector<std::string>& component_names
    );

} // namespace output

#endif // CDX_COVERAGE_OUTPUT_COVERAGE_H